### ISSUE TITLE
minion.t may fail

### ISSUE THREAD

**Issue by eserte** [jhthorsen/mojo-ioloop-readwritefork#11]
On some of my smoker systems t/minion.t fails:
```
Not a HASH reference at /usr/perl5.22.0p/lib/site_perl/5.22.0/Minion.pm line 61.
t/minion.t ............. 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

I think this happens if Minion::Backend::SQLite is too old --- maybe 2.x is not enough here.

**Comment by jhthorsen** [comment]
I think this has been fixed in recent version.
