### ISSUE TITLE
Mojo::Reactor::Poll version consumes quite a bit of CPU through polling for child process exit

### ISSUE THREAD

**Issue by greencoloured** [jhthorsen/mojo-ioloop-readwritefork#16]
Just wondering why you are polling for the process exiting rather than using SIGCHLD? As I noticed this was using up quite a bit of CPU compared to the `Mojo::Reactor::EV` version. 

I see `WAIT_PID_INTERVAL`  can be tuned, but to my tastes using a SIGCHLD handler would be the neater option.

**Comment by jhthorsen** [comment]
This is a known issue. I don't know how to fix this. I suggest installing Mojo::Reactor::EV.

**Comment by jhthorsen** [comment]
I can't depend on SIGCHLD, since it might be "taken" by other part of the perl program.

I hope 5e6c6ceeb96345b653e6b39443b7c1c5e69ea1e2 makes things a bit better for you.

**Comment by greencoloured** [comment]
yes. I had seen that from reading your code. I actually ended up writing my own implementation that didn't have the same restriction. 

should probably have closed the ticket earlier.
