### ISSUE TITLE
Code in the document does not work.

### ISSUE THREAD

**Issue by lucas1** [jhthorsen/mojo-ioloop-readwritefork#17]
Code:
$fork->on(read => sub { ... })->run_p("bash", -c => q(echo $YIKES foo bar baz))->wait;

Error:
Can't call method "run_p" on unblessed reference

Work with:
$fork->run_p("bash", -c => q(echo $YIKES foo bar baz))->wait;

Thank you for this good module.

**Comment by lucas1** [comment]
Solved, I was using the old version. Sorry.

**Comment by lucas1** [comment]
Code:

    package Storage::Model::Command::Bash;
    use Mojo::Base 'MojoX::Model';
    use Mojo::IOLoop::ReadWriteFork;
    
    sub run {
        my ($self, $command) = @_;
    
        if ($command !~ /^$/) {
            my $fork = Mojo::IOLoop::ReadWriteFork->new;
    
            my $data = '';
    
            $fork->on(finish => sub {
                Mojo::IOLoop->stop;
            });
    
            $fork->on(error => sub { warn $_[1] });
    
            $fork->conduit({type => 'pty'});
    
            $fork->on(read => sub {
                  my ($fork, $buf) = @_;
                  
                  $data .= $buf;
            })->run_p('bash', -c => $command)->wait;
    
            return $data;
        }
    
        return;
    }
    
    1;

Test:

    use Test::More;
    
    use_ok('Storage');
    
    my $app = Storage->new;
    
    # create folder
    my $folder_tmp = (time + int(rand(99999)));
    $app->app->model('command-bash')->run('mkdir ./tmp/' . $folder_tmp);
    
    ok(-d './tmp/' . $folder_tmp, 'Test create folder');
    
    # delete folder
    rmdir('./tmp/' . $folder_tmp);
    
    ok(!-d './tmp/' . $folder_tmp, 'Test delete folder');
    
    done_testing;

**Comment by jhthorsen** [comment]
Thanks for reporting in. on() returns the callback, so that's why the SYNOPSIS example was wrong. When that is said, maybe you want to use `run_and_capture_p()`?

```
sub run {
  my ($self, $command) = @_;
  return unless length $command;
  my $fork = Mojo::IOLoop::ReadWriteFork->new;

  my $data;
  $fork->conduit({type => 'pty'});
  $fork->run_and_capture_p('bash', -c => $command)->then(sub {
    my $asset = shift;
    $data = $asset->slurp;
  })->wait;

  return $data;
}
```

**Comment by lucas1** [comment]
I was using method run with Mojo::IOLoop->delay and Mojo::IOLoop->wait before, but this has been removed. Now I'm using run_p(...)->wait work good, only a question run_p(...)->wait is a better alternative to Mojo::IOLoop->delay and Mojo::IOLoop->wait? 

Thanks.

**Comment by jhthorsen** [comment]
It's pretty much the same. I'm not sure why you don't just use IPC::Run3 if all you want is the output in blocking fashion.

**Comment by lucas1** [comment]
Thanks for the tip.
