### ISSUE TITLE
Passing environment for program in start() 

### ISSUE THREAD

**Issue by HEM42** [jhthorsen/mojo-ioloop-readwritefork#5]
Today when you want to dynamically pass on env to the script you want to run, you will have to specify the $ENV{SOME_SPECIALS} before start

```
$ENV{SOME_SPECIAL_DEBUG} = 1;
$fork->start( program => $script_name, program_args => [@args] );
```

Maybe this can be done with an extra parameter for start instead;

```
$fork->start( program => $script_name, program_args => [@args], program_env => $program_env );
```

Seems much cleaner, doing it at run time of the script instead of before forking

**Comment by jhthorsen** [comment]
Can you explain how that is better?

**Comment by HEM42** [comment]
We had an exchange of mails a year back, and I totally forgot about this. Send you a proposed patch on this on on the 4/5-2015. But I never got to create an issue back then.

Im not sure its better, than it makes the code look a bit cleaner .

```
--- /Mojo/IOLoop/ReadWriteFork.pm   2015-04-28 15:14:02.000000000 +0200
+++ /Mojo/IOLoop/ReadWriteFork.pm   2015-05-03 16:34:00.000000000 +0200
@@ -275,6 +275,7 @@
   $| = 1;

   $ENV{$_} = $args->{env}{$_} for keys %{$args->{env}};
+  $ENV{$_} = $args->{program_env}{$_} for keys %{$args->{program_env}};

   if (ref $args->{program} eq 'CODE') {
   $! = 0;
```

**Comment by jhthorsen** [comment]
Would you say these variables would override or be in addition to %ENV? I would like if "program_env" overrides %ENV.

**Comment by HEM42** [comment]
I like the idea of program_env overriding %ENV, makes it clear what you pass on to the script

**Comment by jhthorsen** [comment]
I made the variable shorter: It's called just "env", since it was already in the code.

Thank you for your feedback 👍
