### ISSUE TITLE
Mojolicious server with RWF does not close pipe filehandles

### ISSUE THREAD

**Issue by nils-a-r** [jhthorsen/mojo-ioloop-readwritefork#7]
The server below, when run with "perl $file daemon", keeps the pipe conduits created by run() open until the server stops.
It can be tested by repeatedly doing "curl http://localhost:3000" and look at the increasing number of FIFOs owned by the perl process with lsof.

I don't know if this is a usage issue, a bug in RWF or a bug somewhere else. Any advice will be appreciated.

```
#!perl

use Mojo::Base -strict;
use Mojo::IOLoop::ReadWriteFork;
use Mojolicious;

server()->start;

sub server {
    my $app = Mojolicious->new;

    $app->routes->get('/' => sub {
        my $self = shift->render_later;
        my $fork = Mojo::IOLoop::ReadWriteFork->new;
        my $result = '';

        $self->stash(fork => $fork);

        $fork->on(close => sub {
            my($fork, $exit_value, $signal) = @_;
            $self->render(json => {output => $result, exit_value => $exit_value});
         });

        $fork->on(read => sub {
            my($fork, $buffer) = @_; # $buffer = both STDERR and STDOUT
            $result .= $buffer;
        });

        $fork->run("uptime");
    });

    $app;
}
```

**Comment by jhthorsen** [comment]
Sorry for the late response! I've tried to figure out a nice way to prevent the leak, but the best I could come up with is to delete the fork from the "close" event: https://github.com/jhthorsen/mojo-ioloop-readwritefork/commit/9d99a3245da0817cf27f4f2efa63d6585d6efe0d#diff-e7feee730e2d4a1bad402df4483f0792R20

I want to investigate it further, before I close this issue, but that's at least one way to fix it.

**Comment by jhthorsen** [comment]
I think this is actually the only way to break the cycle, by manually deleting the fork object from the stash. I mean... I don't think perl can magically know when to release it.

**Comment by nils-a-r** [comment]
That did the trick. Thanks for your time!

**Comment by jhthorsen** [comment]
Sure! Anytime Nils 😄
